trigger: none

pr: none

jobs:
- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: release
    platforms:
    - Linux_x64
    - Linux_arm
    - Linux_arm64
    - Windows_NT_x86
    - Windows_NT_x64

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: test-job.yml
    buildConfig: release
    platforms:
    - Linux_x64
    - Linux_arm
    - Linux_arm64
    - Windows_NT_x86
    - Windows_NT_x64
    helixQueueGroup: ci
    jobParameters:
      testGroup: gc-reliability
